blogApp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title=StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

blogApp/main/routes.py
from blogApp.models import Post
from flask import render_template, request, Blueprint

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page = 3, page = page)
    return render_template('home.html', posts = posts)

@main.route('/about')
def about():
    return render_template('about.html', title = "Barca")

blogApp/posts/routes.py
from flask import Blueprint

from blogApp.models import User, Post
from blogApp.posts.forms import PostForm
from blogApp import db
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)

@login_required
@posts.route('/post/new', methods = ['GET', 'POST'])
def newPost():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title = form.title.data, content = form.content.data, 
                    author = current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", 'success')
        return redirect(url_for('main.home'))
    return render_template('createPost.html', title = 'New Post', 
                           legend = 'New Post', form = form)



@posts.route('/post/<int:postID>')
def post(postID):
    post = Post.query.get_or_404(postID)
    return render_template('post.html', title = post.title, post = post)

@login_required
@posts.route('/post/<int:postID>/update', methods = ['GET', 'POST'])
def updatePost(postID):
    post = Post.query.get_or_404(postID)
    if post.author!=current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', postID = post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('createPost.html', title = 'Update Post', 
                           legend = 'Update Post', form = form)

@login_required
@posts.route('/post/<int:postID>/delete', methods = ['POST'])
def deletePost(postID):
    post = Post.query.get_or_404(postID)
    if post.author!=current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

blogApp/users/routes.py
from blogApp.models import User, Post
from blogApp.users.forms import (RegisterationForm, LoginForm, UpdateAccountForm, 
                           RequestResetForm, ResetPasswordForm)
from blogApp import db, bcrypt
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from blogApp.users.utils import sendResetEmail, savePicture

users = Blueprint('users', __name__)


@users.route('/register', methods = ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, email = form.email.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created. You can now log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title = 'Register', form=form)

@users.route('/login', methods = ['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember = form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Unsuccessful login! Please check email and password', 'danger')
    return render_template('login.html', title = 'Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods = ['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            pictureFile = savePicture(form.picture.data)
            current_user.imageFile = pictureFile

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated.", 'success')
        return redirect(url_for('users.account'))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename = 'profile_pics/' + current_user.imageFile)
    return render_template('account.html', title = 'Account', 
                           image_file = image_file, form = form)


@users.route("/user/<string:username>")
def userPosts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username = username).first_or_404()
    posts = Post.query.filter_by(author = user)\
        .order_by(Post.date_posted.desc())\
        .paginate(per_page = 3, page = page)
    return render_template('userPosts.html', posts = posts, user = user)


@users.route('/resetPassword', methods = ['GET', 'POST'])
def resetRequest():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        sendResetEmail(user)
        flash('An email has been sent with instructions to reset password', 'info')
        return redirect(url_for('users.login'))
    return render_template('resetRequests.html', title = 'Reset Password', form = form)

@users.route('/resetPassword/<token>', methods = ['GET', 'POST'])
def resetPassword(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    user = User.verifyResetToken(token)
    if user is None:
        flash('That is an invalid or expired link!', 'warning')
        return redirect(url_for('users.resetRequest'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You can now log in.', 'success')
        return redirect(url_for('users.login'))
    
    return render_template('resetPassword.html', title = 'Reset Password', form = form)

blogApp/templates/about.html
{% extends 'layout.html' %}

{% block content %}
    <h1>About Page</h1>
{% endblock content%}

blogApp/templates/account.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username}}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
        </div>
        <div class="content">
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account Info</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class = "invalid-feedback">
                                {% for error in form.username.errors%}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
    
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
    
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class = "invalid-feedback">
                                {% for error in form.email.errors%}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors%}
                                <span class="text-danger">{{ error }}</span><br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info")}}
                </div>
            </form>
        </div>
    </div>
{% endblock content%}

blogApp/templates/createPost.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}

                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.title.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.content.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>

        </form>
    </div>
{% endblock content%}

blogApp/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    {% for post in posts.items %}
    <article class="media content-section">
      <img src="{{url_for('static', filename = 'profile_pics/' + post.author.imageFile)}}" class="rounded-circle article-img">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.userPosts', username=post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', postID = post.id) }}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)%}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb4" href="{{ url_for('main.home', page = page_num)}}"> {{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb4" href="{{ url_for('main.home', page = page_num)}}"> {{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content%}

blogApp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
              <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{url_for('posts.newPost')}}">New Post</a>
              <a class="nav-item nav-link" href="{{url_for('users.account')}}">Account</a>
                <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories = true) %}
            {% if messages%}
              {% for category, message in messages%}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blogApp/templates/login.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.email.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.password.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-check">
                    {{ form.remember(class="form-check-input")}}
                    {{ form.remember.label(class="form-check-label")}}
                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
                <small class="text-muted ml-2">
                    <a href="{{url_for('users.resetRequest')}}">Forgot Password?</a>
                </small>
            </div>    

        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
    
{% endblock content%}

blogApp/templates/post.html
{% extends 'layout.html' %}

{% block content %}
    <article class="media content-section">
        <img src="{{url_for('static', filename = 'profile_pics/' + post.author.imageFile)}}" class="rounded-circle article-img">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mr-1 my-1" href="{{url_for('posts.updatePost', postID = post.id)}}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
            </div>
            <h2 class = "article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{url_for('posts.deletePost', postID = post.id)}}" method="POST">
                <input class="btn btn-danger" value="Delete" type="submit">
            </form>
            </div>
        </div>
        </div>
    </div>
{% endblock content%}

blogApp/templates/register.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.username.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.email.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.password.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.confirmPassword.label(class="form-control-label") }}
                    {% if form.confirmPassword.errors %}
                        {{ form.confirmPassword(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.confirmPassword.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirmPassword(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
    
{% endblock content%}

blogApp/templates/resetPassword.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.password.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.confirmPassword.label(class="form-control-label") }}
                    {% if form.confirmPassword.errors %}
                        {{ form.confirmPassword(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.confirmPassword.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirmPassword(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>

        </form>
    </div>
    
{% endblock content%}

blogApp/templates/resetRequests.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class = "invalid-feedback">
                            {% for error in form.email.errors%}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>

        </form>
    </div>
    
{% endblock content%}

blogApp/templates/userPosts.html
{% extends 'layout.html' %}

{% block content %}

    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>

    {% for post in posts.items %}
    <article class="media content-section">
      <img src="{{url_for('static', filename = 'profile_pics/' + post.author.imageFile)}}" class="rounded-circle article-img">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.userPosts', username=post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', postID = post.id) }}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)%}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb4" href="{{ url_for('users.userPosts', page = page_num, username = user.username)}}"> {{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb4" href="{{ url_for('users.userPosts', page = page_num, username = user.username)}}"> {{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content%}